# Generated by Django 2.1.3 on 2018-11-22 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qytcloud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vmdb',
            name='vm_global_ip',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='vmdb',
            name='vm_ip',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='vmdb',
            name='vm_status',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='vmdb',
            name='vm_summary',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='vmdb',
            name='vm_webconsole_url',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
