# Generated by Django 2.1.3 on 2018-11-23 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qytcloud', '0002_auto_20181122_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='vmdb',
            name='vm_cpu_cores',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='vmdb',
            name='vm_disk_space_G',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='vmdb',
            name='vm_mem_G',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='vmdb',
            name='vm_nics',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='vmdb',
            name='vm_nics_speed_M',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='vmdb',
            name='vm_global_ip',
            field=models.GenericIPAddressField(),
        ),
        migrations.AlterField(
            model_name='vmdb',
            name='vm_ip',
            field=models.GenericIPAddressField(),
        ),
        migrations.AlterField(
            model_name='vmdb',
            name='vm_webconsole_url',
            field=models.URLField(blank=True),
        ),
    ]
