# Generated by Django 2.1.3 on 2018-11-23 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qytcloud', '0003_auto_20181123_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vmdb',
            name='vm_global_ip',
            field=models.GenericIPAddressField(default='1.1.1.1'),
        ),
        migrations.AlterField(
            model_name='vmdb',
            name='vm_ip',
            field=models.GenericIPAddressField(default='1.1.1.1'),
        ),
    ]
